Repository syan-tibco/tp-helm-charts, pull requests merged in 2023-12, with the labels that each got.

#181 changed appVersion for aks & dp-configure-namespace chart
  charts/dp-config-aks/Chart.yaml
  charts/dp-configure-namespace/Chart.yaml
Labels: enhancement

#184 PDP-1499: readme update for typos
  docs/dp-cluster-workshop/aks/README.md
  docs/dp-cluster-workshop/eks/README.md
Labels: documentation

#200 PDP-1525: Correct the API permission
  docs/dp-cluster-workshop/aks/README.md
Labels: documentation

#202 PDP-1528: mention EMS recommended values
  docs/dp-cluster-workshop/aks/README.md
Labels: documentation

#203 PDP-1528: address comments for using skuName, relclaim policy required in Azure files & chart version should be 1.0.16
  charts/dp-config-aks/Chart.yaml
  charts/dp-config-aks/values.yaml
  docs/dp-cluster-workshop/aks/README.md
Labels: bug

#204 PDP-1528: Fix indetation after uncomment
  docs/dp-cluster-workshop/aks/README.md
Labels: documentation
