Repository syan-tibco/tp-helm-charts, pull requests merged in 2023-11, with the labels that each got.

#126 updated eks wksp recipes to keep in sync with devops repo
  dp-cluster-workshop/eks/README.md
Labels: enhancement

#111 Pdp 1322-II: Fix cleanup
  dp-cluster-workshop/eks/README.md
  dp-cluster-workshop/eks/clean-up.sh
Labels: bug

#132 PDP-1322: incorporate comments from meeting
  dp-cluster-workshop/eks/README.md
  dp-cluster-workshop/eks/clean-up.sh
  dp-cluster-workshop/eks/create-efs.sh
Labels: documentation

#139 Tools minor comment
  dp-cluster-workshop/eks/README.md
Labels: enhancement

#154 PDP-1461: correct public chart url
  docs/dp-cluster-workshop/aks/README.md
  docs/dp-cluster-workshop/eks/README.md
Labels: bug

#157 updated comments in notex.txt
  charts/dp-configure-namespace/Chart.yaml
  charts/dp-configure-namespace/templates/NOTES.txt
Labels: bug

#137 PDP-1336-1340
  charts/dp-configure-namespace/Chart.yaml
  charts/dp-configure-namespace/templates/cluster-role-binding.yaml
  charts/dp-configure-namespace/templates/role-binding.yaml
  charts/dp-configure-namespace/templates/sa.yaml
  charts/dp-configure-namespace/values.yaml
Labels: enhancement

#164 included mountOptions for azure fileshare in aks chart
  charts/dp-config-aks/Chart.yaml
  charts/dp-config-aks/templates/file-sc.yaml
  charts/dp-config-aks/values.yaml
Labels: enhancement

#166 PDP-1499: PM recommended README fixes
  docs/dp-cluster-workshop/aks/README.md
  docs/dp-cluster-workshop/eks/README.md
Labels: documentation

#168 [PDP-1548] added internet-web to dist-lock & dp-secret-cont
  charts/distributed-lock-operator/Chart.yaml
  charts/distributed-lock-operator/templates/deployment.yaml
  charts/dp-core-infrastructure/Chart.yaml
  charts/dp-core-infrastructure/charts/haproxy-ingress/templates/_podtemplate.yaml
  charts/tp-dp-secret-controller/Chart.yaml
  charts/tp-dp-secret-controller/templates/deployment.yaml
  docs/dp-cluster-workshop/aks/README.md
  docs/dp-cluster-workshop/eks/README.md
Labels: enhancement

#170 PDP-1552: Changes to use API server vnet integrated cluster
  docs/dp-cluster-workshop/aks/README.md
  docs/dp-cluster-workshop/aks/aks-cluster-create.sh
  docs/dp-cluster-workshop/aks/pre-aks-cluster-script.sh
Labels: enhancement
